config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: :show
  root "items#index"
  resources :items do
    resources :finds
    collection do
      get 'search'
      get 'ajax'
    end
  end
  get 'items/marker',  to: 'items#marker',  as: :marker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/find.rb
class Find < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :comment, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_one :find, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :studios, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :finds

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze

  validates :password, format: { with: VALID_PASSWORD_REGEX, allow_blank: true }
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname])
  end
end

app/controllers/finds_controller.rb
class FindsController < ApplicationController
  before_action :item_set, only: [:index, :create]
  before_action :skip_user, if: proc { user_signed_in? && current_user.id == @item.user.id }

  def index
    @find = Find.new
    if @item.find.present?
      redirect_to root_path
      return
    end

    redirect_to root_path unless user_signed_in?
  end

  def create
    @find = Find.new(find_params)
    if @find.valid?
      @find.save
      @item.update_attribute(:latitude, 'nil')
      @item.update_attribute(:studios, 'nil')
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def find_params
    params.require(:find).permit(:comment).merge(
      user_id: current_user.id, item_id: params[:item_id]
    )
  end

  def item_set
    @item = Item.find(params[:item_id])
  end

  def skip_user
    redirect_to root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :destroy]
  before_action :item_set, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order('created_at DESC').limit(8)
    @item = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @item = Item.includes(:user).includes(:find).find(params[:id])
  end

  def edit
    if @item.find.present?
      redirect_to action: :index
      return
    end

    if !user_signed_in?
      redirect_to new_user_session_path
    elsif user_signed_in? && !(current_user == @item.user)
      redirect_to action: :index
    end
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    if current_user == @item.user
      @item.destroy
      redirect_to root_path
    end
  end

  def search
    @items = Item.all
    gon.items = @items
    @map_items = []
    unless params[:mapMarkerData].nil?
      @map_items = params[:mapMarkerData]
      partial = render_to_string(partial: 'shared/list', locals: { map_items: @map_items })
      puts partial
      render json: { html: partial }
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :explanation, :address, :image, :color, :feature, :latitude,
                                 :studios).merge(user_id: current_user.id)
  end

  def item_set
    @item = Item.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @items = @user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finds_helper.rb
module FindsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/finds/index.html.erb
<%= render "shared/header" %>

<section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">落とし物情報</h2>
                <!-- Icon Divider-->
                <div class="divider-custom" >
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
              </div>
<div class="item-show">
  <div class="item-box">
    <h1 class="name">
      <%= @item.name %>
    </h1>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>
    <div class="item-price-box">
      <span class="item-postage">
        <h2><%= @item.address %></h2>
      </span>
    </div>
    <div class="item-fotm">
    <%= form_with(model: [@item, @find], multipart: true, local: true) do |f| %>
  
    <%= render 'shared/error_messages', model: f.object %>
    <div class="new-items" >
      <div class="weight-bold-text text-center" >
        <%= "教えてくれた#{@item.user.nickname}さんに感謝の言葉を伝えよう" %>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :comment, class:"items-text", id:"item-name", placeholder:"例） 祖母からもらった大切なペンダントでした！ありがとうございます！" %>
          <div class="sell-btn-contents">
      <%= f.submit "伝える" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    </div>
    </div>
  <% end %>



<footer class="footer text-center" style='width:100% !important; height:200px !important; margin-top :20px;' >
            <div class="container">
                <div class="row">
                    
                <div class="col-lg-12 mb-5 mb-lg-0">
                   <h1 class="text-uppercase mb-4">Drop Item&emsp;
                 
                      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
                       <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
                   </h1>
                </div>
                    
                </div>
            </div>
        </footer>

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">

  </header>
  <%= render "shared/header" %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">落とし物の情報を入力</h2>
    <%= form_with(model: @item, multipart: true, local: true, id: 'new_post') do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 落とし物画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        落とし物の画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
                <div id="previews"></div>
      </div>
    </div>
    <%# /落とし物画像 %>
    <%# 落とし物名と説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        落とし物の名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"落とし物名（必須 20文字まで) 例）定期入れ", maxlength:"20" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          見つけた場所
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :address, class:"items-text", id:"item-address", placeholder:"見つけた場所 例）新宿駅の小田急線改札内で見つけました。",rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          落とし物の説明
          <span class="indispensable">任意</span>
        </div>
        <%= f.text_area :explanation, class:"items-text", id:"item-info", placeholder:"落とし物の説明（必須 1,000文字まで）例）Yamadaさんと書いてありました。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          色
          <span class="indispensable">任意</span>
        </div>
        <%= f.text_field :color, class:"items-text", id:"item-info", placeholder:"例） 赤色の定期入れ" ,rows:"1" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          緯度(google mapのピンの位置から自動的に入力されます）
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :latitude, class:"items-text", id:"lat", placeholder:"google mapのピンの位置から自動的に入力されます" ,rows:"1" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          経度(google mapのピンの位置から自動的に入力されます）
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :studios, class:"items-text", id:"lng", placeholder:"google mapのピンの位置から自動的に入力されます" ,rows:"1" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /落とし物名と説明 %>

 <h2>拾った場所</h2>

<input id="address" type="textbox" value="新宿駅">
<input type="button" value="検索" onclick="codeAddress()">

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
  margin-top : 20px;
  margin-bottom: 20px;
}
</style>


<script>
// 下の1行を追加 
let map
let geocoder
let uluru
let marker
let lat = document.getElementById('lat')
let lng = document.getElementById('lng')


      // Initialize and add the map
      function initMap() {
         geocoder = new google.maps.Geocoder();
        // The location of Uluru
         uluru = { lat: 35.6809591, lng: 139.7673068 };
        // The map, centered at Uluru
         map = new google.maps.Map(document.getElementById("map"), {
          zoom: 16,
          center: uluru,
        });
        // The marker, positioned at Uluru
         marker = new google.maps.Marker({
          position: uluru,
          map: map,
          draggable: true
        });
        
    // マーカーのドロップ（ドラッグ終了）時のイベント
    google.maps.event.addListener( marker, 'dragend', function(ev){
      // イベントの引数evの、プロパティ.latLngが緯度経度。<br />
      lat.value = ev.latLng.lat();
      lng.value = ev.latLng.lng();
    });
  }
 
 function codeAddress(){
  // 入力を取得
  let inputAddress = document.getElementById('address').value;

  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      uluru = results[0].geometry.location;
      
// map.setCenterで地図が移動
map = new google.maps.Map(document.getElementById("map"), {
       center:results[0].geometry.location,
                zoom: 16
      });
              if(marker != null){
        marker.setMap(null);
        }
        marker = null;

// google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location,
          draggable: true,
      });
      document.getElementById('lat').value = uluru.lat();
        document.getElementById('lng').value = uluru.lng();
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }


    google.maps.event.addListener( marker, 'dragend', function(ev){
      // イベントの引数evの、プロパティ.latLngが緯度経度。<br />
      lat.value = ev.latLng.lat();
      lng.value = ev.latLng.lng();
    });
  });
}

    </script>
  </head>
  <body>
   
    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API_KEY']%>&callback=initMap&libraries=&v=weekly"
      async
    ></script>

   <!-- <%=ENV['GOOGLE_MAPS_API_KEY']%> -->
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

<footer class="footer text-center" style='width:100% !important; height:200px !important; margin-top :20px;' >
            <div class="container">
                <div class="row">
                    
                <div class="col-lg-12 mb-5 mb-lg-0">
                   <h1 class="text-uppercase mb-4">Drop Item&emsp;
                 
                      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
                       <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
                   </h1>
                </div>
                    
                </div>
            </div>
        </footer>
</div>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Freelancer - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <%= render "shared/header" %>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-10 ">Drop Item</h1>
                <h4>落とし物を共有しよう</h4>
                
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">落とし物をしてしまった　落とし物を見つけた</br>そんな方へおすすめのアプリ</p>
                    <div class='store-btn'>
                      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
                       <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
                   </div>
            </div>
        </header>
        <!-- Portfolio Section-->

        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">New DropItems</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row justify-content-center item-contents">
 
                    <!-- Portfolio Item 1-->
                    <ul class='item-lists'>
    
      
      <% @items.each do |item| %>
      <li class='list'>
      <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>

          <% if item.find.present? %>
          <div class='sold-out'>
            <span>発見済み</span>
          </div>
          <% end %>

        </div>
        <div class='item-info'>
          <h3 class='item-name2'>
            <%= item.name %></h3>
           <h3 class='item-name'>
            <%= item.address %>
          </h3>
          
        </div>
         <% end %>
      </li>
      <% end %>
     
      <% if @items.blank? %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            落とし物情報サンプル
          </h3>
          <div class='item-price'>
            <span>落とし物名称</span>
            <div class='star-btn'>
              <span class='star-count'>見つけた場所</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>

    </ul>
                    


                </div>
            </div>
        </section>
        <!-- About Section-->
        <section class="page-section bg-primary text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- About Section Content-->
                <div class="row">
                    <div class="col-lg-4 ms-auto"><p class="lead">落とし物を簡単に写真付きで報告！</br>地図や写真付きで投稿して落とし主に情報を届けましょう！</p></div>
                    <div class="col-lg-4 me-auto"><p class="lead">落とし物をしてしまったら依頼してみよう！</br>誰かに代わりに拾ってもらえるかも！</p></div>
                </div>
                <!-- About Section Button-->
                <div class="text-center mt-4">
                    <a class="btn btn-xl btn-outline-light" href="#">
                        <i class="fas fa-download me-2"></i>
                        Free Download!
                    </a>
                </div>
            </div>
        </section>
        <%= link_to(search_items_path, class: 'purchase-btn2') do %>
 <span class='purchase-btn-text'>探す</span>
  <%= image_tag 'search.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
        <%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>登録する</span>
  <%= image_tag 'new2.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  <% end %>
  
        <!-- Footer-->
        <%= render "shared/footer"%>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright @hk52329119</small></div>
        </div>
       
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

app/views/items/show.html.erb
<%= render "shared/header" %>

<section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">落とし物情報</h2>
                <!-- Icon Divider-->
                <div class="divider-custom" >
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
              </div>
<div class="item-show">
  <div class="item-box">
    <h1 class="name">
      <%= @item.name %>
    </h1>
    <div class="item-img-content">
      <%= image_tag @item.image ,class:"item-box-img" %>
      
      <% if @item.find.present? %>
      <div class="sold-out">
        <span>発見済み!!</span>
      </div>
      <% end %>
      
    </div>
    <div class="item-price-box">
      <span class="item-postage">
        <h2><%= @item.address %></h2>
      </span>
    </div>

  <% unless @item.find.present? %>
    <% if user_signed_in? && current_user == @item.user %>
      <%= link_to "商品の編集", edit_item_path, method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
      <%= link_to "削除", item_path, method: :delete, class:"item-destroy" %>
    <% elsif user_signed_in? %>
    <%= link_to "拾った！", item_finds_path(@item), class:"item-red-btn"%>
    <% end %>
  <% end %>
  <% if @item.find.present? %>
 
<div class="item-price-box4 mb-4">
      <div class="item-price-box2">
      <span class="item-postage">
        <h2> <%= @item.find.user.nickname %>さんから感謝のメッセージが届いています</h2>
      </span>
    </div>
    <div class="item-price-box3">
      <h4><%= @item.find.comment %></h4>
      </div>
          </div>
          <% if user_signed_in? && current_user == @item.user %>
          <div class="delete-btn">
       <%= link_to "完了した", item_path, method: :delete, class:"d-btn"%>
       </div>
       <% end %>
    <% end %>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">発見者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">名称</th>
          <td class="detail-value"><%= @item.name %></td>
        </tr>
        <tr>
          <th class="detail-item">落とし物の場所</th>
          <td class="detail-value"><%= @item.address %></td>
        </tr>
        <% if @item.color.present? %>
        <tr>
          <th class="detail-item">落とし物の色</th>
          <td class="detail-value"><%= @item.color %></td>
        </tr>
        <% end %>
        <tr>
          <th class="detail-item">登録された時間</th>
          <td class="detail-value"><%= @item.created_at.to_s(:datetime_jp) %></td>
        </tr>
      </tbody>


    </table>
    
  </div>
  <%# /商品の概要 %>

<h2 class="masthead-heading text-uppercase mb-10 map1 "><span>google map</span></h2>

<div id='map'></div>
<script>
let map
let uluru
let marker


      // Initialize and add the map
      function initMap() {
        // The location of Uluru
         //uluru = { lat: 35.6809591, lng: 139.7673068 };
         uluru = { lat: <%= @item.latitude %>, lng: <%= @item.studios %>};
        // The map, centered at Uluru
         map = new google.maps.Map(document.getElementById("map"), {
          zoom: 16,
          center: uluru,
        });
        // The marker, positioned at Uluru
         marker = new google.maps.Marker({
          position: uluru,
          map: map,
        });
  }
</script>

    <script
      src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API_KEY']%>&callback=initMap&libraries=&v=weekly"
      async
    ></script>

<footer class="footer text-center" style='width:100% !important; height:200px !important; margin-top :20px;' >
            <div class="container">
                <div class="row">
                    
                <div class="col-lg-12 mb-5 mb-lg-0">
                   <h1 class="text-uppercase mb-4">Drop Item&emsp;
                 
                      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
                       <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
                   </h1>
                </div>
                    
                </div>
            </div>
        </footer>
   <%= link_to "https://twitter.com/share?url=https://drop-item.herokuapp.com/items/#{@item.id}&text=#{@item.address}で落とし物を見つけました！落とし物共有サイトならDropItem&hashtags=DropItem", title: 'Twitter', target: '_blank', class: 'add_style purchase-btn' do %>
  <span class='purchase-btn-text'>つぶやく</span>
  <%= image_tag 'twitter.jpg', size: '200x50' ,class: "purchase-btn-icon" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DropItem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer2.html.erb
<footer class="footer text-center" style='width:100% !important; height:200px !important; margin-top :20px;' >
            <div class="container">
                <div class="row">
                    
                <div class="col-lg-12 mb-5 mb-lg-0">
                   <h1 class="text-uppercase mb-4">Drop Item&emsp;
                 
                      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
                       <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
                   </h1>
                </div>
                    
                </div>
            </div>
        </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a><%= link_to 'Drop Item', root_path, class: "navbar-brand" %></a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                    <% if user_signed_in? %>
                        <li class="nav-item mx-0 mx-lg-1"><%= link_to current_user.nickname, user_path(current_user), class: "nav-link py-3 px-0 px-lg-3 rounded" %></li> 
                        <li class="nav-item mx-0 mx-lg-1"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link py-3 px-0 px-lg-3 rounded" %></li> 
                     <% else %>
                        <li class="nav-item mx-0 mx-lg-1"><%= link_to 'ログイン', new_user_session_path, class: "nav-link py-3 px-0 px-lg-3 rounded" %></li>
                        <li class="nav-item mx-0 mx-lg-1"><%= link_to '新規登録', new_user_registration_path, class: "nav-link py-3 px-0 px-lg-3 rounded" %></li>
                    <% end %>
                    </ul>
                </div>
            </div>
        </nav>

app/views/shared/_list.html.erb
<div>
    <h2>付近の落とし物情報</h2>
    <% if @map_items.present? %>
    <p>詳細<p>
        <ul class="sample1">
        <% n = 0 %>
            <% map_items.permit!.to_hash.each do |items| %>
                <li><%= raw("名前【#{items[1]["name"]}】<br/>
               登録された場所【#{items[1]["address"]}】") %></li>
           <%= link_to "詳細ページへ", item_path(items[1]["id"]) , class: "btn" %>

                <% n += 1%>

            <% end %>
        </ul>
    <!-- 初期では↓が表示され、ajaxで↑を表示する -->
    <% else %>
        <p>このコメントが表示される場合は再度読み込みを行なってください</p>
        <p>読み込みエラー javascriptを確認してください</p>
        <div class="col-sm-4">
        </div>
        <a href="javascript:void(0)" type="button" id="id_submit" class="btn btn-save"><i class="material-icons">save</i>ajax!</a>
    <% end %>
</div>